### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by parkr** [osscommunity/maintainers#2]
All open source maintainers have to have a means of communicating with their fellow maintainers. GitHub Issues are usually pretty good for most, but some things can't be taken care of in the issues, and sometimes the issues about actual bugs drown out the administrative issues used for coordination.

How do you communicate within your team? Slack? IRC? Email? Mailing list? How do you make sure the core team is always on the same page?

**Comment by kytrinyx** [comment]
I've tried everything, unfortunately all at the same time. I can say this: don't do that.

I have recently done a couple of things that help:
1. I have a gitter.im chatroom for support questions. People can jump in, and enough people seem to hang out there that people get help. This could be Slack or IRC or whatever, but I think that chat is useful for the off-the-cuff type discussions.
2. I created a specific chat room for a specific effort (doing an audit of all issues + creating a roadmap). This room will go away once the roadmap is complete, but it was useful to have a place for all the noise while it was going on.
3. I created a team for the people who care about the same aspects of maintaining the project, and use `@`organization/team-name and ping them in issues that they should be included in.

I still haven't figured this out, though.

**Comment by parkr** [comment]
Thanks for that insight, @kytrinyx! Pairing the `@org/team` mentions with `@mastahyeti`'s [OctoGAS](https://github.com/mastahyeti/OctoGAS) scripts has really helped streamline triaging issues by email. In terms of communicating with users, we setup a [Discourse site](https://talk.jekyllrb.com) for support questions and general discussion. I think we've reached a pretty good situation with supporting our user base.

I'm concerned now with how to coordinate with the core team, and how to organize to reduce impediments. Breaking down the codebase into discrete parts and creating a team for each is a super great idea! I'd also love to assign each piece to a different core member so each member feels joint ownership of the product. Thoughts?

**Comment by andrew** [comment]
I've been using gitter.im for 24pullrequests and node-sass, it integrates nicely with GitHub. 

For some projects I've also setup a repo on the org called "discussions" where the issues are used as threads, mostly to avoid having to maintain any other software myself and keep all the content in the same place, like a half finished mailing list.

**Comment by kytrinyx** [comment]
The discussions repo is such a good idea. I wish I had thought of that two years ago.

**Comment by parkr** [comment]
Hm! Interesting... the discussions repo sounds cool. What kind of discussions do you have there? How do you direct folks there?

**Comment by andrew** [comment]
@parkr https://github.com/nodeschool/discussions is a good example, discussions are opened as issues in a similar way to a new forum thread, with a readme outlining the rules of the discussions.

**Comment by parkr** [comment]
Thanks y'all. :smile:
